# UKANE PRAISE OGHENE-VARY(AS GRACEOFTHELORD GITHUB)
greek_dict = {
    'house': 'spiti',
    'car': 'aftokinito',
    'book': 'vivlio',
    'water': 'nero',
    'food': 'fagito',
    'friend': 'filos',
    'love': 'agapi',
    'sun': 'ilios',
    'moon': 'fengari',
    'tree': 'dentro',
    'sky': 'ouranos',
    'flower': 'louloudi',
    'mountain': 'vouno',
    'river': 'potami',
    'city': 'poli',
    'dog': 'skylos',
    'cat': 'gata',
    'music': 'mousiki',
    'family': 'oikogeneia',
    'dream': 'oneiro'
}
french_dict = {
    'house': 'maison',
    'car': 'voiture',
    'book': 'livre',
    'water': 'eau',
    'food': 'nourriture',
    'friend': 'ami',
    'love': 'amour',
    'sun': 'soleil',
    'moon': 'lune',
    'tree': 'arbre',
    'sky': 'ciel',
    'flower': 'fleur',
    'mountain': 'montagne',
    'river': 'rivière',
    'city': 'ville',
    'dog': 'chien',
    'cat': 'chat',
    'music': 'musique',
    'family': 'famille',
    'dream': 'rêve'
}

