# UKANE PRAISE OGHENE-VARY(AS GRACEOFTHELORD GITHUB)
greek_dict = {
    'house': 'spiti',
    'car': 'aftokinito',
    'book': 'vivlio',
    'water': 'nero',
    'food': 'fagito',
    'friend': 'filos',
    'love': 'agapi',
    'sun': 'ilios',
    'moon': 'fengari',
    'tree': 'dentro',
    'sky': 'ouranos',
    'flower': 'louloudi',
    'mountain': 'vouno',
    'river': 'potami',
    'city': 'poli',
    'dog': 'skylos',
    'cat': 'gata',
    'music': 'mousiki',
    'family': 'oikogeneia',
    'dream': 'oneiro'
}
# dammy =======
italian_dict = {
    'house': 'casa',
    'car': 'auto',
    'book': 'libro',
    'water': 'acqua',
    'food': 'cibo',
    'friend': 'amico',
    'love': 'amore',
    'sun': 'sole',
    'moon': 'luna',
    'tree': 'albero',
    'sky': 'cielo',
    'flower': 'fiore',
    'mountain': 'montagna',
    'river': 'fiume',
    'city': 'citta',
    'dog': 'cane',
    'cat': 'gatto',
    'music': 'musica',
    'family': 'famiglia',
    'dream': 'sogno'
}
